import type { Metadata } from 'next'
import { Poppins, Inter } from 'next/font/google'
import ReduxProvider from '../store/ReduxProvider'
import './globals.css'

const poppins = Poppins({
    variable: '--font-main-poppins',
    weight: '500',
    subsets: ['latin']
})

const inter = Inter({
    variable: '--font-second-inter',
    weight: ['400', '500', '600', '700'],
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' className={`${poppins.variable} ${inter.variable} h-full antialiased`}>
            <body className='h-screen flex items-center justify-center'>
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    )
}

