services:
  email_test:
    container_name: email_test
    ports:
      - 1080:1080
  db_postgres:
    container_name: db_postgres
    image: postgres:10
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always

